# Server
server.port=8082

#YOUR_UNSPLASH_ACCESS_KEY_HER

# OpenAI
#openai.api.key=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
#openai.api.url=https://api.openai.com/v1/chat/completions
#openai.model=gpt-4o

#GEMINI
#openai.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
#openai.api.key=AIzaSyD7UQH-FvJavfVFX6tuxDLboDSXs60_k0Q
#openai.model=gemini-1.5-flash

#Groq
openai.api.key=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
openai.api.url=https://api.groq.com/openai/v1/chat/completions
openai.model=llama-3.3-70b-versatile

# Unsplash
unsplash.api.key=w2jujoBgd-ywKq1XaCb8wz4DShjFiR8tYJw_ODtU_7E
unsplash.api.url=https://api.unsplash.com
unsplash.results.limit=5

# CORS - allow both frontend apps
cors.allowed.origins=http://localhost:5173,http://localhost:5174

# Logging
logging.level.com.satellite=DEBUG
