# Server
server.port=8082

#YOUR_UNSPLASH_ACCESS_KEY_HERE

# OpenAI
#openai.api.key=YOUR_UNSPLASH_ACCESS_KEY_HERE
#openai.api.url=https://api.openai.com/v1/chat/completions
#openai.model=gpt-4o

#GEMINI
#openai.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
#openai.api.key=YOUR_UNSPLASH_ACCESS_KEY_HERE
#openai.model=gemini-1.5-flash

#Groq
openai.api.key=YOUR_UNSPLASH_ACCESS_KEY_HERE
openai.api.url=https://api.groq.com/openai/v1/chat/completions
openai.model=llama-3.3-70b-versatile

# Unsplash
unsplash.api.key=YOUR_UNSPLASH_ACCESS_KEY_HERE
unsplash.api.url=https://api.unsplash.com
unsplash.results.limit=5

# CORS - allow both frontend apps
cors.allowed.origins=http://localhost:5173,http://localhost:5174

# Logging
logging.level.com.satellite=DEBUG
